apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - www.pavanraga.tk
    secretName: letsencrypt-prod
  rules:
  - host: www.pavanraga.tk
    http:
      paths:
      - path: /tea
        backend:
          serviceName: teasvc
          servicePort: 80
      - path: /coffe
        backend:
          serviceName: coffesvc
          servicePort: 80